---
- hosts: all
  become: true
  tasks:
    - name: Install utils
      apt:
        name:
          - vim
          - tcpdump
          - net-tools
        state: latest
        update_cache: yes
        cache_valid_time: 3600


- hosts: dnsserver
  become: true
  roles:
    - dnsserver


- hosts: mailserver
  become: true
  roles:
    - mailserver
    - firewall
    - common
    - nameserver
    
- hosts: client, client2
  become: true
  roles:
    - common
    - alpineClient
    - nameserver
    
- hosts: switchRouter
  become: true
  roles:
    - switchRouter
