- name: Install Open vSwitch
  apt:
    name: openvswitch-switch
    state: present

- name: Create bridge br0
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: br0
    state: present
    
    
- name: Aggiungi le porte al bridge br0 con i tag VLAN corretti
  openvswitch.openvswitch.openvswitch_port:
    bridge: br0
    port: "{{ item.name }}"
    state: present
    tag: "{{ item.tag }}"
  loop: "{{ ovs_ports }}"
