- name: Install Open vSwitch
  apt:
    name: openvswitch-switch
    state: present

- name: Create bridge br0
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ ovs_bridge }}"
    state: present
    
    
- name: Aggiungi le porte al bridge br0 con i tag VLAN corretti
  openvswitch.openvswitch.openvswitch_port:
    bridge: "{{ ovs_bridge }}"
    port: "{{ item.name }}"
    state: present
    tag: "{{ item.tag }}"
  loop: "{{ ovs_ports }}"


- name: Add internal ports for VLANs
  openvswitch.openvswitch.openvswitch_port:
    bridge: "{{ ovs_bridge }}"
    port: "{{ item.name }}"
    state: present
    tag: "{{ item.tag }}"
  loop: "{{ vlan_interfaces }}"

- name: Set IPs for router interfaces
  ansible.builtin.shell: "ip addr add {{ item.ip_address }}/24 dev {{ item.name }}"
  loop: "{{ vlan_interfaces }}"


- name: Set router interfaces up
  shell: "ip l set {{ item.name }} up"
  loop: "{{ vlan_interfaces }}"

- name: Ensure IP forwarding is enabled
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward = 1'
    state: present
  notify: Reload sysctl