- name: Creazione degli utenti
  user:
    name: "{{ item.name }}"
    home: "{{ item.home }}"  
    shell: "{{ item.shell }}"
    password: "{{ item.password }}"
   #expires: "{{ lookup('pipe', 'date -u --date=\"now + 180 days\" +%s') }}"
  loop: "{{ users }}"


- name: Aggiunta degli utenti al gruppo sudo
  user: 
    name: "{{ item }}"
    groups: sudo
  with_items:
    - test
    - client
    - client2


