- name: Install bind9
  become: true
  apt:
    name:
      - bind9
      - dnsutils

- name: Create log directory for BIND
  ansible.builtin.file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: '0755'


- name: Copy configs
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/bind/" 
    force: yes
  with_fileglob: "{{ role_path }}/files/bind9/*"
  notify: restart bind9
  
  
- name: Set nameserver in resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver\s'
    state: absent

- name: Add nameserver to resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 10.10.10.2'
    create: yes

